apiVersion: serverless.kyma-project.io/v1alpha1
kind: GitRepository
metadata:
    creationTimestamp: null
    name: kyma-examples-repo
    namespace: default
spec:
    url: https://github.com/kwiatekus/examples.git
---
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
    labels:
        app.kubernetes.io/name: event-emitter
    name: event-emitter
    namespace: default
spec:
    baseDir: /incluster_eventing/src/emitter-fn/
    reference: improve-eventing-example
    runtime: nodejs16
    source: kyma-examples-repo
    type: git
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: incoming-http-trigger
  namespace: default
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - handler: allow
    methods:
    - GET
    path: /.*
  service:
    host: incoming
    name: event-emitter
    port: 80
