apiVersion: serverless.kyma-project.io/v1alpha1
kind: GitRepository
metadata:
  creationTimestamp: null
  name: kyma-examples-repo
  namespace: default
spec:
  url: https://github.com/kyma-project/examples.git

---
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  creationTimestamp: null
  name: event-emitter
  namespace: default
spec:
  baseDir: /incluster_eventing/src/emitter-fn/
  reference: function-cicd-example
  runtime: nodejs14
  source: kyma-examples-repo
  type: git

---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  creationTimestamp: null
  name: incoming-http-trigger
  namespace: default
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - handler: allow
    methods:
    - GET
    path: /.*
  service:
    host: incoming
    name: event-emitter
    port: 80

