apiVersion: serverless.kyma-project.io/v1alpha1
kind: GitRepository
metadata:
    name: kyma-examples-repo
    namespace: default
spec:
    url: https://github.com/kwiatekus/examples.git
---
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
    labels:
        app.kubernetes.io/name: event-receiver
    name: event-receiver
    namespace: default
spec:
    baseDir: /incluster_eventing/src/receiver-fn/
    reference: improve-eventing-example
    runtime: nodejs16
    source: kyma-examples-repo
    type: git
---
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: event-receiver
  namespace: default
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.acme.payload.sanitised.v1
  protocol: ""
  protocolsettings: {}
  sink: http://event-receiver.default.svc.cluster.local

