apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
    creationTimestamp: null
    labels:
        app.kubernetes.io/name: event-receiver
    name: event-receiver
    namespace: default
spec:
    deps: |-
        {
          "name": "store-fn",
          "version": "0.0.1",
          "dependencies": {}
        }
    runtime: nodejs16
    source: |-
        module.exports = {
            main: function (event, context) {
                store(event.data)
                return 'Stored'
            }
        }
        let store = (data)=>{
            console.log(`storing data...`)
            console.log(data)
            return data
        }

---
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
    creationTimestamp: null
    name: event-receiver
    namespace: default
spec:
    filter:
        filters:
            - eventSource:
                property: source
                type: exact
                value: ""
              eventType:
                property: type
                type: exact
                value: sap.kyma.custom.acme.payload.sanitised.v1
    protocol: ""
    protocolsettings: {}
    sink: http://event-receiver.default.svc.cluster.local

