name: event-receiver
namespace: default
runtime: nodejs16
source:
    sourceType: inline
subscriptions:
    - name: event-receiver
      protocol: ""
      filter:
        filters:
            - eventSource:
                property: source
                type: exact
                value: ""
              eventType:
                property: type
                type: exact
                value: sap.kyma.custom.acme.payload.sanitised.v1
