name: event-emitter
namespace: default
runtime: nodejs16
source:
    sourceType: inline
apiRules:
    - name: incoming-http-trigger
      service:
        host: incoming
      rules:
        - methods:
            - GET
          accessStrategies:
            - handler: allow